[build]
  command = "npx expo export -p web"
  publish = "dist"

# Redireciona todas as rotas para index.html (SPA - Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
